# A GitHub Actions workflow to verify MkDocs documentation builds successfully on pull requests.
---
name: Verify MkDocs Build
on:
  pull_request:
    branches:
      - master
      - main
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Set up cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
      - run: |
            cd mkdocs
            pip install -r mkdocs_requirements.txt
      - name: Verify MkDocs Build
        id: build
        run: |
          output=$(PYTHONPATH=. mkdocs build -f mkdocs/mkdocs.yml)
          echo "$output"
          status=$(echo "$output" | grep 'Documentation built in')
          echo "status=$status" >> $GITHUB_OUTPUT
      - name: Check Build Status
        run: |
          if [ -z "${{ steps.build.outputs.status }}" ]; then
            echo "MkDocs build failed."
            exit 1
          else
            echo "MkDocs build succeeded."
            echo "${{ steps.build.outputs.status }}"
          fi
          